#!/bin/sh
# Boot heartbeat: proves userspace is alive even if scripts are quiet.
case "$1" in
start)
    (
        exec > /dev/tty0 2>&1
        echo "[boot] === rcS started at $(date +%T) ==="
        i=0
        while [ $i -lt 36 ]; do
            sleep 5
            procs=$(ls /proc | grep -c '^[0-9]')
            echo "[boot] alive ${i}x5s, procs=$procs"
            i=$((i + 1))
        done
    ) &
    ;;
stop) ;;
esac
